package DTO;
// Generated Oct 17, 2017 9:07:48 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cautraloi generated by hbm2java
 */
@Entity
@Table(name = "cautraloi", catalog = "trochoitienganh")
public class Cautraloi implements java.io.Serializable {

	private Integer maTl;
	private Cauhoi cauhoi;
	private String noiDung;
	private int ketQua;

	public Cautraloi() {
	}

	public Cautraloi(Cauhoi cauhoi, String noiDung, int ketQua) {
		this.cauhoi = cauhoi;
		this.noiDung = noiDung;
		this.ketQua = ketQua;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MaTL", unique = true, nullable = false)
	public Integer getMaTl() {
		return this.maTl;
	}

	public void setMaTl(Integer maTl) {
		this.maTl = maTl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaCH", nullable = false)
	public Cauhoi getCauhoi() {
		return this.cauhoi;
	}

	public void setCauhoi(Cauhoi cauhoi) {
		this.cauhoi = cauhoi;
	}

	@Column(name = "NoiDung", nullable = false, length = 65535)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

	@Column(name = "KetQua", nullable = false)
	public int getKetQua() {
		return this.ketQua;
	}

	public void setKetQua(int ketQua) {
		this.ketQua = ketQua;
	}

}
