package DTO;
// Generated Oct 17, 2017 9:07:48 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ctdiem generated by hbm2java
 */
@Entity
@Table(name = "ctdiem", catalog = "trochoitienganh")
public class Ctdiem implements java.io.Serializable {

	private Integer ma;
	private Taikhoan taikhoan;
	private String email;
	private int sodiem;
	private Date ngay;
	private int ketqua;

	public Ctdiem() {
	}

	public Ctdiem(Taikhoan taikhoan, String email, int sodiem, Date ngay, int ketqua) {
		this.taikhoan = taikhoan;
		this.email = email;
		this.sodiem = sodiem;
		this.ngay = ngay;
		this.ketqua = ketqua;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ma", unique = true, nullable = false)
	public Integer getMa() {
		return this.ma;
	}

	public void setMa(Integer ma) {
		this.ma = ma;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaTK", nullable = false)
	public Taikhoan getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(Taikhoan taikhoan) {
		this.taikhoan = taikhoan;
	}

	@Column(name = "email", nullable = false, length = 65535)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Sodiem", nullable = false)
	public int getSodiem() {
		return this.sodiem;
	}

	public void setSodiem(int sodiem) {
		this.sodiem = sodiem;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay", nullable = false, length = 10)
	public Date getNgay() {
		return this.ngay;
	}

	public void setNgay(Date ngay) {
		this.ngay = ngay;
	}

	@Column(name = "ketqua", nullable = false)
	public int getKetqua() {
		return this.ketqua;
	}

	public void setKetqua(int ketqua) {
		this.ketqua = ketqua;
	}

}
